apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: dublinhouse-host
spec:
  hostname: dublinhouse.eastus.cloudapp.azure.com
  acmeProvider:
    email: russmax@dublinstreet.com
  tlsSecret:
    name: dublinhouse-tls