apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dublinhouse-tls-cert
spec:
  secretName: dublinhouse-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "dublinhouse.eastus.cloudapp.azure.com"